spring:
  datasource:
    url: jdbc:mysql://containerization-mysql-db-1:3306/jwt_security
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
#
#spring:
#  datasource:
#    url: jdbc:postgresql://containerization-postgres-db-1:5432/jwt_security
#    username: myuser
#    password: mypassword
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
