version: '3.8'

services:
  authentication-service:
    build: ./authentication
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: jwt_security
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  upload-video-service:
    build: ./uploadVideo
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db
    restart:
      always
    # networks:
    #   - upload

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  video-streamer-service:
    build: ./videoStreamer
    ports:
      - "5173:5173"
    depends_on:
      - file-system-service

  file-system-service:
    build: ./fileSystem
    ports:
      - "3000:3000"
    # networks:
    #   - upload
    # volumes:
    #   - ./fileUpload/uploads:/usr/src/app/uploads  # Assuming your server saves files to an 'uploads' directory

volumes:
  pgdata:

networks:
  upload:
    driver: bridge
